# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: npm install -g npm && corepack enable && npm install yarn && yarn set version stable
  - init: yarn install
  - command: echo "done"

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - redhat.vscode-yaml
    - firsttris.vscode-jest-runner
    - dbaeumer.vscode-eslint
    - vscode-icons-team.vscode-icons
    - IronGeek.vscode-env
    - eamodio.gitlens